Add .NET Core 3.0 support and add multi targets
gabrielweyer/xunit-to-junit pull request #2
Opened 2019-04-26 09:35 UTC by LonghronShen

Add .NET Core 3.0 support and add multi targets

2019-04-27 12:44 UTC, gabrielweyer commented
Thank you for the contribution @LonghronShen. Any reason why you need support for `.NET Core 3` now as we're still a few months away from the official release?

2019-04-27 12:54 UTC, LonghronShen commented
Thank you for the reply! Since the target is not actually binded to any preview version of the .NET Core 3.0 SDK, I think even making this PR published as a non-preview version is still OK because it will surely be usable for the future RTM version of the .NET Core 3 SDK. Or can we publish a preview version?

2019-04-29 11:24 UTC, gabrielweyer requested changes
Your motivation makes sense. I don't have have any issue with supporting `.NET Core 3` now.

Could you please address my comments and I'll merge your `Pull Request`?

2019-04-29 11:24 UTC, gabrielweyer commented on src/xUnitToJUnit/xUnitToJUnit.csproj
> +    <TargetFrameworks>netcoreapp2.1;netcoreapp2.2;netcoreapp3.0</TargetFrameworks>
There is no need to target `netcoreapp2.2`. Since `.NET Core 2.0`, [applications automatically roll forward to the latest minor version installed on a system](https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-2-1#roll-forward).

2019-04-29 11:24 UTC, gabrielweyer commented on src/xUnitToJUnit/xUnitToJUnit.csproj
> +    <VersionPrefix>1.0.2</VersionPrefix>
Is this required? I was able to pack the tool without it.

2019-04-29 11:24 UTC, gabrielweyer commented on src/xUnitToJUnit/xUnitToJUnit.csproj
> +    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
Is this required? I was able to pack the tool without it.

2019-04-29 13:20 UTC, LonghronShen commented on src/xUnitToJUnit/xUnitToJUnit.csproj
> +    <TargetFrameworks>netcoreapp2.1;netcoreapp2.2;netcoreapp3.0</TargetFrameworks>
OK, you are right so I'll remove the **.NET Core 2.1** platform.

2019-04-29 13:23 UTC, LonghronShen commented on src/xUnitToJUnit/xUnitToJUnit.csproj
> +    <VersionPrefix>1.0.2</VersionPrefix>
Oh, this is just because of my local packaging action. As for a CI enabled scenario, a explicit version should be avoided. I'll remove it.

2019-04-29 13:23 UTC, LonghronShen commented on src/xUnitToJUnit/xUnitToJUnit.csproj
> +    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
Oh, this is just because of my local packaging action. As for a CI enabled scenario, a explicit version should be avoided. I'll remove it.

2019-04-30 10:35 UTC, gabrielweyer approved these changes

2019-04-30 10:50 UTC, merged

2019-04-30 10:59 UTC, gabrielweyer commented
Thank you for your contribution, your `Pull Request` has been merged and the `NuGet` gallery will index the new version within `30` minutes.